# Generated by Django 4.2.30 on 2026-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('History', 'History'), ('English', 'English'), ('Other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/pdfs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField()),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('query_count', models.IntegerField(default=0)),
            ],
        ),
    ]
